application: scrobbular-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: images/scrobbular_16.png
  upload: images/scrobbular_16.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /.*
  script: hello.app
